#!/bin/bash

spaces (){
	hyprctl workspaces -j | jq -Mc 'map({id: .id | tostring, windows: .windows}) | sort_by(.id | tonumber)'
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
