#!/bin/sh

signal() {
    link=`cat /proc/net/wireless | awk 'NR==3{print int($3)}'`
	ss="$(( $link * 100 / 70 ))"
	slot=`expr $ss % 4`
	case "$slot" in
		0) echo "󰤟" $ss ;;
		1) echo "󰤢" $ss ;;
		2) echo "󰤥" $ss ;;
		3) echo "󰤨" $ss ;;
		*) echo "󰤩" 0 ;;
	esac
}

case $1 in
    icon) signal | awk '{print $1}' ;;
    signal) signal | awk '{print $2}' ;;
esac
