#!/bin/sh

signal() {
  dBm=`cat /proc/net/wireless | awk 'NR==3{print int($4)}'`
  if [ -30 -le $dBm ] && [ $dBm -gt -67 ]; then
    echo "󰤨" $dBm
  elif [ -70 -le $dBm ] && [ $dBm -gt -80 ]; then
    echo "󰤥" $dBm
  elif [ -80 -le $dBm ] && [ $dBm -gt -90 ]; then
    echo "󰤢" $dBm
  elif [ -90 -le $dBm ] && [ $dBm -gt -90 ]; then
    echo "󰤟" $dBm
  else
    echo "󰤩" 0
  fi
}

case $1 in
  icon) signal | awk '{print $1}' ;;
  signal) signal | awk '{print $2}' ;;
esac
